#!/bin/bash
echo ##################### Package
aws cloudformation package --template-file template.yaml --output-template-file serverless-output.yaml --s3-bucket brandonvio-re-demo-api

echo ##################### Deploy
aws cloudformation deploy --template-file serverless-output.yaml --stack-name redemo --capabilities CAPABILITY_IAM